**Домашнее задание 1**

Решите предложенные задания с использованием модуля NumPy. Использование условий и циклов крайне нежелательно (списковые включения это тоже цикл!), за это будут снижаться баллы.
Все задания равноценны. В каждой задаче постарайтесь придумать несколько решений. В задачах, где обязательно необходимо предложить хотя бы два решения, об этом написано. Решением должен быть Jupyter notebook / ссылка на Colab

Под массивом (если не указано иное), понимается одномерный массив. Для большей части задач не указан размер массива. Это значит, что код должен работать корректно для любого размера массива

In [1]:
import numpy as np

1. Создайте массив 3x3, состоящий из True. Напишите минимум два варианта решения


In [2]:
arr_true_1 = np.array([[True] * 3] * 3)
arr_true_2 = np.array([[True, True, True], [True, True, True], [True, True, True]])
arr_true_3 = np.ones((3, 3), dtype=bool)
arr_true_1, arr_true_2, arr_true_3

(array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]))

2. Замените в массиве все нечетные положительные числа на -1

In [4]:
arr = np.arange(-5, 10)
print(arr)
arr[(arr %2 != 0) & (arr > 0)]=-1
arr

[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9]


array([-5, -4, -3, -2, -1,  0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Найдите все числа, встречающиеся в 1 и 2 массивах

In [5]:
arr1 = np.array([[1,2,3], [4,6,7], [43,12,213]])
arr2 = np.array([[2,3,9], [1,4,213]])
arr1_arr2 = np.intersect1d(arr1,arr2)
arr1_arr2

array([  1,   2,   3,   4, 213])

4. Дана функция maxx, работающая с двумя числами. Напишите обертку над ней, которая будет работать с двумя np.array (одинакового размера) и будет применять функцию maxx поэлементно (вместо maxx может быть любая другая кастомная функция)


```
def maxx(x, y):
	    return x if x >= y else y
```




In [7]:
def maxx(x, y):
        return x if x >= y else y

In [8]:
arr1 = np.array([[1,2,3], [4,6,7]])
arr2 = np.array([[2,3,9], [1,4,213]])
func = np.vectorize(maxx)
res = func(arr1,arr2)
res

array([[  2,   3,   9],
       [  4,   6, 213]])

5. Дана матрица 3х3. Поменяйте местами 1 и 2 столбцы матрицы.

In [9]:
arr1 = np.array([[1,2,3], [4,6,7], [52,12,34]])
tmp = arr1[0].copy()
arr1[0] = arr1[1]
arr1[1] = tmp
arr1

array([[ 4,  6,  7],
       [ 1,  2,  3],
       [52, 12, 34]])

6. Поменяйте опции (```np.set_printoptions```), чтобы при выводе numpy.array отображалось не более 6 элементов

In [10]:
np.set_printoptions(threshold=6)
arr1 = np.array([2,3,4,6,7,52,12,34])
arr1

array([ 2,  3,  4, ..., 52, 12, 34])

7. В данном массиве замените все числа, меньшие 0 на 0, а большие 255 на 255. Напишите минимум два варианта решения

In [11]:
np.set_printoptions()

In [12]:
arr1 = np.array([2,-32,-1,21512,22332])
arr1[(arr1<0)]=0
arr1[(arr1>255)]=255
arr1

array([  2,   0,   0, 255, 255])

In [13]:
arr1 = np.array([2, -32, -1, 21512, 22332])
arr1 = np.clip(arr1, 0, 255)
arr1

array([  2,   0,   0, 255, 255])

8. Выведите позиции топ-5 максимальных элементов в массиве. Попробуйте решить задачу за линейную сложность относительно числа элементов

In [32]:
arr1 = np.array([2, -32, -1, 21512, 22332,21412,142124,8796789,6768])
arr1[np.argpartition(arr1, -5)][-5:]

array([  21412,   21512,   22332, 8796789,  142124])

9. Преобразуйте массив массивов в одномерный массив.

In [15]:
arr1 = np.array([[1,2,3], [4,6,7], [52,12,34]])
arr1.ravel()

array([ 1,  2,  3, ..., 52, 12, 34])

10. Найдите максимум в каждой строке двумерного массива

In [16]:
arr1 = np.array([[1,2,3], [4,6,7], [52,12,34]])
np.amax(arr1, axis = 1)

array([ 3,  7, 52])

11. Удалите все np.nan из массива

In [17]:
arr1 = np.array([1,np.nan,3, np.nan,6,7, 52,12,np.nan])
arr1[np.isnan(arr1)!=True]

array([ 1.,  3.,  6.,  7., 52., 12.])

12. Найдите индекс пятого повторения числа 1 в массиве (считаем, что в массиве есть хотя бы пять единиц)

In [18]:
arr1 = np.array([1,2,3,1,1,4,6,7,1,52,1,12,34])
np.where(arr1==1)[0][-1]

10

13. В квадратной матрице 5х5 из нулей получить ромб из 1, который касается середин сторон квадрата. Решите задачу как для полного ромба (внутри все 1), так и для полого (1 по границе, внутри 0):

```
полный           полый
0 0 1 0 0       0 0 1 0 0
0 1 1 1 0       0 1 0 1 0
1 1 1 1 1       1 0 0 0 1
0 1 1 1 0       0 1 0 1 0
0 0 1 0 0       0 0 1 0 0
```

In [ ]:
# your code here

14. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки

In [21]:
arr1 = np.random.randint(1,100, size=(5,7))
np.delete(arr1, [2,4], axis = 1)

array([[20, 29, 24, 18, 64],
       [30, 30,  6, 54, 72],
       [50, 85, 13, 85,  2],
       [21, 85, 64, 40, 11],
       [64, 63, 49, 82,  2]])

15. Вычислите [скользящее среднее](https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%BE%D0%BB%D1%8C%D0%B7%D1%8F%D1%89%D0%B0%D1%8F_%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D1%8F%D1%8F) в окне ширины 3

In [22]:
arr1 = np.array([1,2,3,1,1,4,6,7,1,52,1,12,34])
w = 3
np.convolve(arr1, np.ones(w)/w, 'valid')

array([ 2.        ,  2.        ,  1.66666667, ..., 18.        ,
       21.66666667, 15.66666667])